config/routes.rb
Rails.application.routes.draw do
  resources :cloth_items do
    member do
      get :photo
    end
  end

  devise_for :accounts, controllers: {
    registrations: 'account/registrations',
  }
  get 'demo', to: 'demo#index'
  root 'demo#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cloth_item.rb
class ClothItem < ApplicationRecord
  include ActionView::Helpers::NumberHelper
  MAX_SIZE = 1.megabytes
  ALLOWED_TYPES = %w[image/jpeg image/gif image/png]

  belongs_to :user
  belongs_to :color, optional: true
  belongs_to :category, optional: true
  has_and_belongs_to_many :tags

  validates_presence_of :category, message: "must be selected"
  validates_presence_of :color, message: "must be selected"
  validates_presence_of :photo, message: "must be selected"

  scope :of_category, -> (name) {
    category = Category.find_by(name: name)
    where category: category
  }

  scope :of_color, -> (names) {
    colors = Color.where(name: names)
    where color: colors
  }

  def add_tags(tag_names)
    tag_names.each { |tag_name| add_tag(tag_name) }
  end

  def update_tags!(tag_names)
    ActiveRecord::Base.transaction do
      tags.destroy_all
      add_tags(tag_names)
      save!
    end
  end

  def add_tag(tag_name)
    existing_tag = Tag.find_by(name: tag_name)
    if existing_tag
      tags << existing_tag
    else
      tags.build(name: tag_name)
    end
  end

  def update_photo!(uploaded_file, dir:)
    return unless uploaded_file
    check_photo_size(uploaded_file)
    check_photo_type(uploaded_file)
    delete_photo(dir: dir) if self.photo
    update! photo: photo_name(uploaded_file)
    save_photo(dir, photo, uploaded_file)
  end

  def delete_photo(dir:)
    photo_path = File.join(dir, photo)
    File.delete(photo_path)
  end

  private

  def photo_name(uploaded_file)
    ext = File.extname(uploaded_file.original_filename)
    name = Time.now.to_f.to_s
    return "#{name}#{ext}"
  end

  def check_photo_size(uploaded_file)
    return if uploaded_file.size <= MAX_SIZE
    max_size = number_to_human_size(MAX_SIZE)
    raise PhotoError, "Photo size can't be bigger than #{max_size}"
  end

  def check_photo_type(uploaded_file)
    return if ALLOWED_TYPES.include? uploaded_file.content_type
    allowed_types = ALLOWED_TYPES.join(', ')
    raise PhotoError, "Only photo formats allowed: #{allowed_types}"
  end

  def save_photo(dir, photo_filename, uploaded_file)
    Dir.mkdir dir unless Dir.exist? dir
    photo_path = File.join(dir, photo_filename)
    File.open(photo_path, 'wb') do |file|
      file.write(uploaded_file.read)
    end
  end

end

class ClothItem::PhotoError < StandardError; end

app/controllers/cloth_items_controller.rb
class ClothItemsController < ApplicationController
  require 'action_view'
  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::TextHelper
  before_action :authenticate_account!
  before_action :authorize, only: [:show, :edit, :update, :destroy]

  def index
    session[:category] = params[:category] if params[:category]
    session[:category] = nil if params[:destroy_category]
    session[:color] ||= []
    if params[:color]
      session[:color] << params[:color] unless session[:color].include? params[:color]
    end
    session[:color] = [] if params[:destroy_all_colors]
    session[:color].delete(params[:destroy_color]) if params[:destroy_color]
    @cloth_items = current_user.cloth_items.paginate(page: params[:page],
                                                     per_page: 24)

    @cloth_items = @cloth_items.of_category(session[:category]) if session[:category]
    @cloth_items = @cloth_items.of_color(session[:color]) if session[:color].any?
    @active_color = session[:color]
    @active_category = session[:category]
  end

  def show
    @cloth_item = ClothItem.find(params[:id])
  end

  def new
    @cloth_item = ClothItem.new
    @tags = Tag.all
  end

  def create
    @tags = Tag.all

    params_not_empty? or return

    @cloth_item = current_user.cloth_items.build(basic_params)

    ActiveRecord::Base.transaction do
      @cloth_item.update_photo!(params[:cloth_item][:photo], dir: photos_dir)
      if params[:cloth_item][:tags]
        entered_tags = params[:cloth_item][:tags].split(",")
        @cloth_item.add_tags(entered_tags)
      end
      @cloth_item.save!
      flash[:success] = 'Cloth item has been added'
    end
    redirect_to cloth_item_path(@cloth_item)
    rescue ClothItem::PhotoError => e
      flash[:danger] = e.message
      render :new
    rescue ActiveRecord::ActiveRecordError => e
      render :new
  end

  def edit
    @cloth_item = ClothItem.find(params[:id])
    @tags = Tag.all
  end

  def update
    @cloth_item = ClothItem.find(params[:id])
    @cloth_item.update!(basic_params)
    if params[:cloth_item][:photo]
      @cloth_item.update_photo!(params[:cloth_item][:photo], dir: photos_dir)
    end
    entered_tags = params[:cloth_item][:tags].split(",")
    @cloth_item.update_tags!(entered_tags)
    redirect_to cloth_item_path(@cloth_item)
    flash[:success] = 'Cloth item has been updated'
    rescue ClothItem::PhotoError => e
      flash[:danger] = e.message
      render :edit
    rescue ActiveRecord::ActiveRecordError => e
      flash[:danger] = 'Failed to update cloth item'
      render :edit
  end

  def destroy
    ActiveRecord::Base.transaction do
      cloth_item = ClothItem.find(params[:id])
      cloth_item.destroy!
      cloth_item.delete_photo(dir: photos_dir)
      flash[:danger] = "Cloth item has been deleted"
      redirect_back(fallback_location: cloth_items_path)
    end
    rescue ActiveRecord::ActiveRecordError => e
    rescue SystemCallError => e
      flash[:danger] = "Failed to delete cloth item"
      redirect_to cloth_items_path
  end

  def photo
    cloth_item = ClothItem.find(params[:id])
    if cloth_item.user != current_user
      head 401
      return
    end
    file_path = photos_dir.join(cloth_item.photo).to_s
    file_name = cloth_item.photo
    send_file(file_path, filename: file_name )
  end

  private

    def basic_params
      params.require(:cloth_item).permit(:category_id, :color_id)
    end

    def params_not_empty?
      return true if params[:cloth_item]
      @cloth_item = current_user.cloth_items.build
      @cloth_item.validate
      render :new
      return false
    end

    def photos_dir
      Rails.root.join("uploads/photos", current_user.id.to_s)
    end

    def authorize
      cloth_item = ClothItem.find(params[:id])
      unless cloth_item.user == current_user
        redirect_to(root_url)
        flash[:danger] = "this cloth item doesn't belong to you"
      end
    end
end

app/helpers/cloth_items_helper.rb
module ClothItemsHelper
end

app/views/cloth_items/_remove_all.html.erb
<%= render 'remove_filter',
            path: cloth_items_path(destroy_all_colors: true, destroy_category: true),
            caption: "remove filters",
            button: "btn btn-danger btn-sm" %>

app/views/cloth_items/_remove_category.html.erb
<%= render 'remove_filter',
            path: cloth_items_path(destroy_category: true),
            caption: session[:category],
            button: "btn btn-info btn-sm" %>

app/views/cloth_items/_remove_color.html.erb
<%= render 'remove_filter',
            path: cloth_items_path(destroy_color: name),
            caption: name,
            button: "btn btn-info btn-sm" %>

app/views/cloth_items/_remove_filter.html.erb
<%= link_to path, class: button do %>
  <div><%= caption %></div>
  <span class="glyphicon glyphicon-remove"></span>
<% end %>

app/views/cloth_items/_show_tags.html.erb
<% if cloth_item.tags.any? %>
<% limit ||= 999 %>
  <% cloth_item.tags.first(limit).map do |tag| %>
    <div class="tag">
      <%= tag.name %>
    </div>
  <% end %>
<% end %>

app/views/cloth_items/edit.html.erb
<%= form_for(@cloth_item) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <p>
    <h3> Category </h3>
    <% Category.all.each do |category| %>
      <div class="radio-buttons">
        <%= f.radio_button(:category_id, category.id) %>
        <%= f.label "category_id_#{category.id}", category.name %>
      </div>
    <% end %>
  </p>

  <p>
    <h3 class="radio_name"> Color </h3>
    <% Color.all.each do |color| %>
      <div class="radio-buttons">
        <%= f.radio_button(:color_id, color.id) %>
        <%= f.label "color_id_#{color.id}", color.name %>
      </div>
    <% end %>
  </p>

  <p>
    <h3 class="radio_name"> Photo </h3>
    <div class="photo_minature">
      <div class="gallery_img"
           style="background-image:
           url('<%= photo_cloth_item_path(@cloth_item) %>');">
      </div>
    </div>
    <%= f.file_field :photo, accept: 'image/jpeg,image/gif,image/png' %>
  </p>

  <p>
    <h3>Tags</h3>
    <%= f.text_field :tags,
                     'value' => f.object.tags.map(&:name).join(', ')
                      %>
  </p>

  <script type="text/javascript">
    var tags_list = [
      <%= @tags.map{|tag| "{ name: '#{tag.name}' }" }.join(', ').html_safe %>
    ];
  </script>
  <script type="text/javascript">
    $(function() {
      var tags = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: tags_list
      });
      tags.initialize();
      $('#cloth_item_tags').tagsinput({
        typeaheadjs: {
          displayKey: 'name',
          source: tags.ttAdapter()
        }
      });
    });
  </script>

  <style type="text/css">
    .tt-query {
      box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
    }

    .tt-hint {
      color: #999
    }

    .tt-menu {
      width: 422px;
      margin: 12px 0;
      padding: 8px 0;
      background-color: #fff;
      border: 1px solid #ccc;
      border: 1px solid rgba(0, 0, 0, 0.2);
      border-radius: 8px;
      box-shadow: 0 5px 10px rgba(0,0,0,.2);
    }

    .tt-suggestion {
      padding: 3px 20px;
      font-size: 18px;
      line-height: 24px;
    }

    .tt-suggestion:hover {
      cursor: pointer;
      color: #fff;
      background-color: #0097cf;
    }

    .tt-suggestion.tt-cursor {
      color: #fff;
      background-color: #0097cf;

    }

    .tt-suggestion p {
      margin: 0;
    }
  </style>

  <p>
    <%= f.submit "Save changes", class: "button" %>
  </p>
<% end %>

app/views/cloth_items/index.html.erb
<h1>My clothes</h1>
<%= "Filter:" %>
<%= "Show all" unless session[:category] || session[:color].any? %>

<%= render 'remove_category' if session[:category] %>

<% if session[:color] %>
  <% session[:color].each do |color| %>
    <%= render 'remove_color', name: color %>
  <% end %>
<% end %>

<% if session[:category] && session[:color].any? || session[:color].count > 1 %>
  <%= render 'remove_all' %>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <%= will_paginate %>
  </div>
</div>

<div class="row gallery">
  <% @cloth_items.each do |cloth_item| %>
    <div class="col-lg-3 col-md-4 col-sm-6">
      <div class="row max-width">
        <div class="back" data-cloth-item-id="<%= cloth_item.id %>">
          <div class="delete">
            <div class="vertically-centered">
              <p>Are you sure you want to delete cloth item?</p>
              <a href="#"
                 class="cancel_cloth_item_deletion"
                 data-cloth-item-id="<%= cloth_item.id %>"
              >
                <span class="glyphicon glyphicon-circle-arrow-left"></span> cancel
              </a>
              <%= link_to cloth_item_path(cloth_item),
                          method: :delete,
                          'data-cloth-item-id' => cloth_item.id,
                          'class' => 'delete_cloth_item' do %>
                <span class="glyphicon glyphicon-trash"></span> delete
              <% end %>
            </div>
          </div>
        </div>
        <%= link_to cloth_item_path(cloth_item) do %>
          <div class="gallery_img"
               style="background-image: url('<%= photo_cloth_item_path(cloth_item) %>');">
          </div>
        <% end %>
        <div class="col-xs-11 caption">
          <%= render 'show_tags', cloth_item: cloth_item, limit: 1 %>
        </div>
        <div class="col-xs-1 caption">
          <a href="#"
             class="cloth_item_delete"
             data-cloth-item-id="<%= cloth_item.id %>"
          >
            <span class="glyphicon glyphicon-trash"></span>
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= will_paginate %>
  </div>
</div>

app/views/cloth_items/new.html.erb
<%= form_for(@cloth_item) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <p>
    <h3> Category </h3>
    <% Category.all.each do |category| %>
      <div class="radio-buttons">
        <%= f.radio_button(:category_id, category.id) %>
        <%= f.label "category_id_#{category.id}", category.name %>
      </div>
    <% end %>
  </p>

  <p>
    <h3 class="radio_name"> Color </h3>
    <% Color.all.each do |color| %>
      <div class="radio-buttons">
        <%= f.radio_button(:color_id, color.id) %>
        <%= f.label "color_id_#{color.id}", color.name %>
      </div>
    <% end %>
  </p>

  <p>
    <h3 class="radio_name"> Photo </h3>
    <%= f.file_field :photo, accept: 'image/jpeg,image/gif,image/png' %>
  </p>

  <p>
    <h3>Tags</h3>
    <%= f.text_field :tags,
                     'value' => f.object.tags.map(&:name).join(', ')
                      %>
  </p>

  <script type="text/javascript">
    var tags_list = [
      <%= @tags.map{|tag| "{ name: '#{tag.name}' }" }.join(', ').html_safe %>
    ];
  </script>
  <script type="text/javascript">
    $(function() {
      var tags = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: tags_list
      });
      tags.initialize();
      $('#cloth_item_tags').tagsinput({
        typeaheadjs: {
          displayKey: 'name',
          source: tags.ttAdapter()
        }
      });
    });
  </script>

  <style type="text/css">
    .tt-query {
      box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
    }

    .tt-hint {
      color: #999
    }

    .tt-menu {
      width: 422px;
      margin: 12px 0;
      padding: 8px 0;
      background-color: #fff;
      border: 1px solid #ccc;
      border: 1px solid rgba(0, 0, 0, 0.2);
      border-radius: 8px;
      box-shadow: 0 5px 10px rgba(0,0,0,.2);
    }

    .tt-suggestion {
      padding: 3px 20px;
      font-size: 18px;
      line-height: 24px;
    }

    .tt-suggestion:hover {
      cursor: pointer;
      color: #fff;
      background-color: #0097cf;
    }

    .tt-suggestion.tt-cursor {
      color: #fff;
      background-color: #0097cf;

    }

    .tt-suggestion p {
      margin: 0;
    }
  </style>

  <p>
    <%= f.submit "Add Cloth Item", class: "button" %>
  </p>
<% end %>

app/views/cloth_items/show.html.erb
<h4>Category: <%= @cloth_item.category.name %></h4>
<h4>Color: <%= @cloth_item.color.name %></h4>

<%= render 'show_tags', cloth_item: @cloth_item %>

<div class="row">
  <div class="col-sm-12 show_img">
    <img src='<%= photo_cloth_item_path(@cloth_item) %>' alt='cloth item photo' />
    <div class='row links'>
      <%= link_to 'edit', edit_cloth_item_path(@cloth_item), class: "button" %>

      <%= link_to 'back', cloth_items_path, class: "button back" %>
    </div>
  </div>
</div>