config/routes.rb
Rails.application.routes.draw do
  resources :cloth_items do
    member do
      get :photo
    end
  end

  devise_for :accounts, controllers: {
    registrations: 'account/registrations',
  }
  get 'demo', to: 'demo#index'
  root 'demo#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_category_item.html.erb
<li class="list-group-item <%= @active_category == name ? 'active' : '' %>">
  <%= link_to cloth_items_path(category: name) do %>
    <div> <%= name %> </div>
  <% end %>
</li>

app/views/layouts/_color_item.html.erb
<%= render 'layouts/side_menu_color',
           path: cloth_items_path(color: name),
           label: name,
           current_value: @active_color %>

app/views/layouts/_demo.html.erb
<div id="main">
    <h1>Welcome to MyCubby </h1>

    <h2>This is the home page for the MyCubby application.</h2>
    <input type="text" name="nico" value="asd">
    <br />
    asdasd  asd asd as asd  asd asd asd asda sasad asd asd
    <br />
    asdasd  asd asd as asd  asd asd asd asda sasad asd asd
    <br />
    asdasd  asd asd as asd  asd asd asd asda sasad asd asd
    <br />
    asdasd  asd asd as asd  asd asd asd asda sasad asd asd
    <br />
    asdasd  asd asd as asd  asd asd asd asda sasad asd asd
    <br />
    asdasd  asd asd as asd  asd asd asd asda sasad asd asd
    <br />
    asdasd  asd asd as asd  asd asd asd asda sasad asd asd
    <br />
    asdasd  asd asd as asd  asd asd asd asda sasad asd asd
    <br />
    asdasd  asd asd as asd  asd asd asd asda sasad asd asd
    <br />
    asdasd  asd asd as asd  asd asd asd asda sasad asd asd
</div>

app/views/layouts/_footer.html.erb
<nav>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "*,.*", '#' %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Item1", '#' %></li>
      <li><%= link_to "Item2", '#' %></li>
      <li><%= link_to "^..^", '#' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_header.html.erb
<div id="header">
  <h1>Header</h1>
</div>

app/views/layouts/_main_menu.html.erb
<nav>
  <div class="navbar-header">
    <button type="button"
            class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#navbar"
            aria-expanded="false"
            aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div id="navbar" class="collapse navbar-collapse">
    <% if account_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to "Hello #{current_account.user.name}", '#' %></li>
        <li>
          <%= link_to "Log out", destroy_account_session_path, method: :delete %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "My clothes", cloth_items_path %></li>
        <li><%= link_to "My sets", '#' %></li>
        <li><%= link_to "New item", new_cloth_item_path %></li>
      </ul>
    <% else %>
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign up", new_account_registration_path %></li>
      <li><%= link_to "Login", new_account_session_path %></li>
    </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_side_menu.html.erb
<div id="side_menu">
  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <h4 class="panel-title" id="accordion">
        <button class="btn_accordion" data-toggle="collapse" data-parent="#accordion" data-target="#collapse1">
        Categories
        </button>
      </h4>
      <div id="collapse1" class="panel-collapse collapse">
        <ul class="list-group">
          <%= render 'layouts/category_item', name: 'Dresses' %>
          <%= render 'layouts/category_item', name: 'Tops' %>
          <%= render 'layouts/category_item', name: 'Shirts&Blouses' %>
          <%= render 'layouts/category_item', name: 'Cardigans&Jumpers' %>
          <%= render 'layouts/category_item', name: 'Jackets' %>
          <%= render 'layouts/category_item', name: 'Coates' %>
          <%= render 'layouts/category_item', name: 'Shorts' %>
          <%= render 'layouts/category_item', name: 'Trousers' %>
          <%= render 'layouts/category_item', name: 'Jeans' %>
          <%= render 'layouts/category_item', name: 'Skirts' %>
          <%= render 'layouts/category_item', name: 'Shoes' %>
          <%= render 'layouts/category_item', name: 'Accessories' %>
          <%= render 'layouts/category_item', name: 'Sportswear' %>
          <%= render 'layouts/category_item', name: 'Miscellaneous' %>
        </ul>
      </div>
    </div>
    <div class="panel panel-default">
      <h4 class="panel-title">
        <button class="btn_accordion" data-toggle="collapse" data-parent="#accordion" data-target="#collapse2">
        Occasion
        </button>
      </h4>
      <div id="collapse2" class="panel-collapse collapse">
        <ul class="list-group">
          <li class="list-group-item">One</li>
          <li class="list-group-item">Two</li>
          <li class="list-group-item">Three</li>
          <li class="list-group-item">One</li>
          <li class="list-group-item">Two</li>
          <li class="list-group-item">Three</li>
        </ul>
      </div>
    </div>
    <div class="panel panel-default">
      <h4 class="panel-title">
        <button class="btn_accordion" data-toggle="collapse" data-parent="#accordion" data-target="#collapse3">
        Color
        </button>
      </h4>
      <div id="collapse3" class="panel-collapse collapse">
        <ul class="list-group">
          <%= render 'layouts/color_item', name: 'black' %>
          <%= render 'layouts/color_item', name: 'white' %>
          <%= render 'layouts/color_item', name: 'grey' %>
          <%= render 'layouts/color_item', name: 'brown' %>
          <%= render 'layouts/color_item', name: 'violet' %>
          <%= render 'layouts/color_item', name: 'blue' %>
          <%= render 'layouts/color_item', name: 'green' %>
          <%= render 'layouts/color_item', name: 'yellow' %>
          <%= render 'layouts/color_item', name: 'red' %>
          <%= render 'layouts/color_item', name: 'pink' %>
          <%= render 'layouts/color_item', name: 'orange' %>
          <%= render 'layouts/color_item', name: 'multicolor' %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_side_menu_color.html.erb
<li class="list-group-item <%= current_value && current_value.include?(label) ? 'active' : '' %>">
  <%= link_to path do %>
    <div> <%= label %> </div>
  <% end %>
</li>

app/views/layouts/_tray.html.erb
<div id="tray">
  <h1>Tray</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCubby</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="nav-container">
      <div class="container" >
        <div class="row">
          <div id="main-menu" class="col-sm-12 navbar navbar-inverse">
            <%= render 'layouts/main_menu' %>
          </div>
        </div>
      </div>
    </div>

    <div class="container hidden-xs">
      <div class="aside-tray">
        <%= render 'layouts/tray' %>
      </div>
    </div>

    <div class="container hidden-xs">
      <div class="aside">
        <div class="aside_margin">
          <div class="aside_inner">
            <%= render 'layouts/side_menu' %>
          </div>
        </div>
      </div>
    </div>

    <div class="container" >
      <div id="content" class="row">
        <div class="col-sm-12">
          <%= render 'layouts/header' %>
          <% flash.each do |message_type, message| %>
            <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>

    <div id="footer" class="container">
      <div class="row">
        <div class="col-sm-12 navbar navbar-inverse">
          <%= render 'layouts/footer' %>
        </div>
      </div>
    </div>
  </body>
</html>